# Generated by Django 4.0.1 on 2022-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_pw', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
