# Generated by Django 4.0.1 on 2022-01-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundingapp', '0004_fundingfunc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingBoardS',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('language', models.CharField(max_length=30, null=True)),
                ('target', models.CharField(max_length=30, null=True)),
                ('eqA', models.IntegerField()),
                ('eqB', models.IntegerField()),
                ('eqC', models.IntegerField()),
                ('imgefile', models.CharField(max_length=30, null=True)),
                ('intro', models.TextField(null=True)),
                ('background', models.TextField(null=True)),
                ('objectstive', models.TextField(null=True)),
                ('developContent', models.TextField(null=True)),
                ('fund_goal_price', models.IntegerField()),
                ('fund_total_price', models.IntegerField()),
                ('regi_date', models.DateField()),
            ],
        ),
    ]
