# Generated by Django 4.0.1 on 2022-01-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundingapp', '0005_fundingboards'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundingBoardS',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='FundingFunc',
        ),
    ]
