# Generated by Django 4.0.1 on 2022-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingBoard',
            fields=[
                ('board_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('language_text', models.CharField(max_length=30, null=True)),
                ('target', models.CharField(max_length=30, null=True)),
                ('intro', models.TextField(null=True)),
                ('file_name', models.CharField(max_length=30, null=True)),
                ('background_text', models.CharField(max_length=200, null=True)),
                ('object_text', models.CharField(max_length=200, null=True)),
                ('develop_content', models.CharField(max_length=200, null=True)),
                ('func_a_price', models.IntegerField()),
                ('func_b_price', models.IntegerField()),
                ('func_c_price', models.IntegerField()),
                ('fund_goal_price', models.IntegerField()),
                ('fund_total_price', models.IntegerField()),
                ('regi_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'FundingBoard',
                'managed': False,
            },
        ),
    ]
