# Generated by Django 4.0.1 on 2022-01-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, unique=True)),
                ('user_pw', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30, null=True)),
                ('user_email', models.EmailField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
