# Generated by Django 4.0.1 on 2022-01-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
